# Generated by Django 4.2.29 on 2026-04-27 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solvedproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedproblem',
            name='solved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
